# Generated by Django 5.2 on 2025-05-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.CharField()),
                ('date', models.DateField()),
                ('description', models.CharField()),
            ],
        ),
    ]
